branch-defaults:
  master:
    environment: CoolbizBackend-env-2
environment-defaults:
  CoolbizBackend-env:
    branch: null
    repository: null
global:
  application_name: coolbiz_backend
  default_ec2_keyname: autoscale
  default_platform: arn:aws:elasticbeanstalk:us-east-1::platform/Python 3.6 running
    on 64bit Amazon Linux/2.7.6
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
